// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package gui

import "fyne.io/fyne/v2"

var ResourceIconSvg = &fyne.StaticResource{
	StaticName: "icon.svg",
	StaticContent: []byte(
		"<svg width=\"64\" height=\"64\" viewBox=\"0 0 64 64\" xmlns=\"http://www.w3.org/2000/svg\">\n  <circle cx=\"32\" cy=\"32\" r=\"30\" fill=\"#4F46E5\" stroke=\"#312E81\" stroke-width=\"2\"/>\n  <rect x=\"28\" y=\"16\" width=\"8\" height=\"16\" rx=\"4\" fill=\"white\"/>\n  <path d=\"M20 30 Q20 40 32 40 Q44 40 44 30\" stroke=\"white\" stroke-width=\"2\" fill=\"none\"/>\n  <line x1=\"32\" y1=\"40\" x2=\"32\" y2=\"48\" stroke=\"white\" stroke-width=\"2\"/>\n  <line x1=\"26\" y1=\"48\" x2=\"38\" y2=\"48\" stroke=\"white\" stroke-width=\"2\"/>\n  <circle cx=\"32\" cy=\"20\" r=\"1.5\" fill=\"#E5E7EB\"/>\n  <circle cx=\"32\" cy=\"24\" r=\"1.5\" fill=\"#E5E7EB\"/>\n  <circle cx=\"32\" cy=\"28\" r=\"1.5\" fill=\"#E5E7EB\"/>\n</svg>"),
}
